### ISSUE TITLE
your replicate instruct-pix2pix doesn't seem to work

### ISSUE THREAD

**Issue by yosun** [chenxwh/cog-themed-diffusion#2]
https://replicate.com/p/h7rwh652tbdjxcizaydw7zk3ne

**Comment by chenxwh** [comment]
Hi, have you tried this example directly using the [python](https://github.com/timothybrooks/instruct-pix2pix#edit-a-single-image) instructions from the original repo (or other demos) to see whether it produces similar results?

I think it is unlikely a Replicate issue since Replicate does not change the nature of the model but wraps all in a docker image.
